## Q-LEARNING

In [61]:
!pip install gym
import gym
import numpy as np

In [76]:
env=gym.make('FrozenLake-v1')

In [63]:
STATES=env.observation_space.n
ACTIONS=env.action_space.n

In [64]:
Q=np.zeros((STATES,ACTIONS))
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
#env.reset()

In [66]:
#action=env.action_space.sample()
#action

In [67]:
#new_state,reward,done,info,probability=env.step(action)

In [68]:
#env.render()

In [69]:
EPISODES=1000
STEPS=100
LEARNING_RATE=0.81
GAMMA=0.96
RENDER=True
epsilon=.9

In [40]:
#if np.random.uniform(0,1)<epslion:
#   action=env.action_space.sample()
#else:
#    action=np.argmax((Q[state:]))


In [44]:
#Q[state,action]=Q[state,action]+LEARNING_RATE*(reward+GAMMA*np.max(Q[new_state,:])-Q[state,action])

In [74]:
rewards = []
for episode in range(EPISODES):
    state = env.reset()[0]
    for _ in range(STEPS):  # Fixed typo: STESP to STEPS
        if RENDER:
            env.render()
        if np.random.uniform(0, 1) < epsilon:  # Fixed typo: epslion to epsilon
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state, :])  # Fixed typo: (Q[state:]) to (Q[state, :])
            
        new_state, reward, done, info,_ = env.step(action)  # Removed unused variable 'probability'
        Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMMA * np.max(Q[new_state, :]) - Q[state, action])
        state = new_state
        if done:
            rewards.append(reward)
            epsilon -= 0.001  # Fixed typo: epslion to epsilon
            break


In [75]:
print(Q)

[[2.54824199e-01 3.05345228e-02 2.82616992e-02 3.30956764e-02]
 [6.91351916e-05 3.39079559e-05 3.38339398e-03 2.50314434e-01]
 [7.56391418e-03 9.66822224e-03 8.57302764e-03 2.90596555e-01]
 [1.99622132e-03 4.40294870e-03 2.28331920e-03 1.28055951e-01]
 [2.37121548e-01 2.11017949e-02 1.62982202e-02 1.86753866e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.39445322e-04 9.27084595e-07 3.16458613e-02 3.32888185e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.40975191e-02 1.77285470e-02 2.17105102e-02 2.85966062e-01]
 [1.60075283e-02 3.80491358e-01 1.60561475e-02 6.52904426e-03]
 [2.58348934e-01 5.22356493e-03 5.73747547e-03 4.21633903e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.45350809e-02 2.67288588e-02 4.51802318e-01 2.19517452e-02]
 [1.99479352e-01 8.98819449e-01 1.73289592e-01 1.28594221e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000